"""add trainer_applications table

Revision ID: c6259593335b
Revises: 009_advanced_workout
Create Date: 2026-04-20 08:19:13.171659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6259593335b'
down_revision: Union[str, None] = '009_advanced_workout'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_applications_id'), 'trainer_applications', ['id'], unique=False)
    op.create_index(op.f('ix_trainer_applications_user_id'), 'trainer_applications', ['user_id'], unique=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_constraint('nutrition_goals_user_id_key', 'nutrition_goals', type_='unique')
    op.drop_index('ix_nutrition_goals_user_id', table_name='nutrition_goals')
    op.create_index(op.f('ix_nutrition_goals_user_id'), 'nutrition_goals', ['user_id'], unique=True)
    op.alter_column('program_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('program_assignments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_program_assignments_id'), 'program_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_program_days_id'), 'program_days', ['id'], unique=False)
    op.alter_column('program_exercises', 'exercise_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('program_exercises', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('program_exercises', 'rest_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('90'))
    op.create_index(op.f('ix_program_exercises_id'), 'program_exercises', ['id'], unique=False)
    op.alter_column('user_achievements', 'earned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_user_achievements_user', table_name='user_achievements')
    op.drop_column('user_xp', 'updated_at')
    op.alter_column('workout_programs', 'duration_weeks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('workout_programs', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'intermediate'::character varying"))
    op.alter_column('workout_programs', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('workout_programs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_workout_programs_id'), 'workout_programs', ['id'], unique=False)
    op.alter_column('workout_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'strength'::character varying"))
    op.create_index(op.f('ix_workout_templates_id'), 'workout_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_templates_id'), table_name='workout_templates')
    op.alter_column('workout_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'strength'::character varying"))
    op.drop_index(op.f('ix_workout_programs_id'), table_name='workout_programs')
    op.alter_column('workout_programs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_programs', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('workout_programs', 'difficulty',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'intermediate'::character varying"))
    op.alter_column('workout_programs', 'duration_weeks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.add_column('user_xp', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('idx_user_achievements_user', 'user_achievements', ['user_id'], unique=False)
    op.alter_column('user_achievements', 'earned_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_program_exercises_id'), table_name='program_exercises')
    op.alter_column('program_exercises', 'rest_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('90'))
    op.alter_column('program_exercises', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('program_exercises', 'exercise_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_program_days_id'), table_name='program_days')
    op.drop_index(op.f('ix_program_assignments_id'), table_name='program_assignments')
    op.alter_column('program_assignments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('program_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_nutrition_goals_user_id'), table_name='nutrition_goals')
    op.create_index('ix_nutrition_goals_user_id', 'nutrition_goals', ['user_id'], unique=False)
    op.create_unique_constraint('nutrition_goals_user_id_key', 'nutrition_goals', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_trainer_applications_user_id'), table_name='trainer_applications')
    op.drop_index(op.f('ix_trainer_applications_id'), table_name='trainer_applications')
    op.drop_table('trainer_applications')
    # ### end Alembic commands ###
