"""40 achievement definitions covering all categories."""

ACHIEVEMENTS = [
    # ── WORKOUT (10) ────────────────────────────────────────────────────────
    {
        "key": "first_workout",
        "name": "First Step",
        "description": "Complete your very first workout",
        "icon_name": "Dumbbell",
        "category": "workout",
        "xp_reward": 50,
        "requirement_type": "workout_count",
        "requirement_value": 1,
        "rarity": "common",
    },
    {
        "key": "workouts_5",
        "name": "Getting Started",
        "description": "Complete 5 workouts",
        "icon_name": "Dumbbell",
        "category": "workout",
        "xp_reward": 75,
        "requirement_type": "workout_count",
        "requirement_value": 5,
        "rarity": "common",
    },
    {
        "key": "workouts_10",
        "name": "Ten Down",
        "description": "Complete 10 workouts",
        "icon_name": "Flame",
        "category": "workout",
        "xp_reward": 100,
        "requirement_type": "workout_count",
        "requirement_value": 10,
        "rarity": "common",
    },
    {
        "key": "workouts_25",
        "name": "Quarter Century",
        "description": "Complete 25 workouts",
        "icon_name": "Trophy",
        "category": "workout",
        "xp_reward": 150,
        "requirement_type": "workout_count",
        "requirement_value": 25,
        "rarity": "rare",
    },
    {
        "key": "workouts_50",
        "name": "Half Century",
        "description": "Complete 50 workouts",
        "icon_name": "Trophy",
        "category": "workout",
        "xp_reward": 250,
        "requirement_type": "workout_count",
        "requirement_value": 50,
        "rarity": "rare",
    },
    {
        "key": "workouts_100",
        "name": "Century Club",
        "description": "Complete 100 workouts",
        "icon_name": "Crown",
        "category": "workout",
        "xp_reward": 500,
        "requirement_type": "workout_count",
        "requirement_value": 100,
        "rarity": "epic",
    },
    {
        "key": "workouts_250",
        "name": "Grinder",
        "description": "Complete 250 workouts",
        "icon_name": "Crown",
        "category": "workout",
        "xp_reward": 1000,
        "requirement_type": "workout_count",
        "requirement_value": 250,
        "rarity": "epic",
    },
    {
        "key": "workouts_500",
        "name": "Iron Will",
        "description": "Complete 500 workouts",
        "icon_name": "Star",
        "category": "workout",
        "xp_reward": 2000,
        "requirement_type": "workout_count",
        "requirement_value": 500,
        "rarity": "legendary",
    },
    {
        "key": "volume_10000",
        "name": "Heavy Lifter",
        "description": "Lift a total of 10,000 kg across all workouts",
        "icon_name": "Weight",
        "category": "workout",
        "xp_reward": 200,
        "requirement_type": "total_volume_kg",
        "requirement_value": 10000,
        "rarity": "rare",
    },
    {
        "key": "volume_100000",
        "name": "Tonnage Master",
        "description": "Lift a total of 100,000 kg",
        "icon_name": "Zap",
        "category": "workout",
        "xp_reward": 1000,
        "requirement_type": "total_volume_kg",
        "requirement_value": 100000,
        "rarity": "legendary",
    },

    # ── STRENGTH / PRs (8) ──────────────────────────────────────────────────
    {
        "key": "first_pr",
        "name": "New Record",
        "description": "Achieve your first personal record",
        "icon_name": "TrendingUp",
        "category": "strength",
        "xp_reward": 100,
        "requirement_type": "pr_count",
        "requirement_value": 1,
        "rarity": "common",
    },
    {
        "key": "prs_5",
        "name": "Breaking Limits",
        "description": "Achieve 5 personal records",
        "icon_name": "TrendingUp",
        "category": "strength",
        "xp_reward": 150,
        "requirement_type": "pr_count",
        "requirement_value": 5,
        "rarity": "common",
    },
    {
        "key": "prs_10",
        "name": "Record Breaker",
        "description": "Achieve 10 personal records",
        "icon_name": "Trophy",
        "category": "strength",
        "xp_reward": 200,
        "requirement_type": "pr_count",
        "requirement_value": 10,
        "rarity": "rare",
    },
    {
        "key": "prs_25",
        "name": "Unstoppable",
        "description": "Achieve 25 personal records",
        "icon_name": "Zap",
        "category": "strength",
        "xp_reward": 400,
        "requirement_type": "pr_count",
        "requirement_value": 25,
        "rarity": "rare",
    },
    {
        "key": "prs_50",
        "name": "Legend in the Making",
        "description": "Achieve 50 personal records",
        "icon_name": "Star",
        "category": "strength",
        "xp_reward": 750,
        "requirement_type": "pr_count",
        "requirement_value": 50,
        "rarity": "epic",
    },
    {
        "key": "prs_100",
        "name": "Strength God",
        "description": "Achieve 100 personal records",
        "icon_name": "Crown",
        "category": "strength",
        "xp_reward": 1500,
        "requirement_type": "pr_count",
        "requirement_value": 100,
        "rarity": "legendary",
    },
    {
        "key": "volume_5000",
        "name": "Volume King",
        "description": "Lift 5,000 kg in a single workout",
        "icon_name": "Flame",
        "category": "strength",
        "xp_reward": 300,
        "requirement_type": "single_workout_volume",
        "requirement_value": 5000,
        "rarity": "epic",
    },
    {
        "key": "exercises_variety",
        "name": "All-Rounder",
        "description": "Log 20 different exercises",
        "icon_name": "LayoutGrid",
        "category": "strength",
        "xp_reward": 150,
        "requirement_type": "exercise_variety",
        "requirement_value": 20,
        "rarity": "rare",
    },

    # ── CONSISTENCY / STREAKS (8) ────────────────────────────────────────────
    {
        "key": "streak_3",
        "name": "Three-Peat",
        "description": "Work out 3 days in a row",
        "icon_name": "Flame",
        "category": "consistency",
        "xp_reward": 75,
        "requirement_type": "streak_days",
        "requirement_value": 3,
        "rarity": "common",
    },
    {
        "key": "streak_7",
        "name": "Week Warrior",
        "description": "Work out 7 days in a row",
        "icon_name": "Flame",
        "category": "consistency",
        "xp_reward": 200,
        "requirement_type": "streak_days",
        "requirement_value": 7,
        "rarity": "common",
    },
    {
        "key": "streak_14",
        "name": "Two-Week Beast",
        "description": "Work out 14 days in a row",
        "icon_name": "Zap",
        "category": "consistency",
        "xp_reward": 350,
        "requirement_type": "streak_days",
        "requirement_value": 14,
        "rarity": "rare",
    },
    {
        "key": "streak_30",
        "name": "Monthly Grind",
        "description": "Work out 30 days in a row",
        "icon_name": "Trophy",
        "category": "consistency",
        "xp_reward": 500,
        "requirement_type": "streak_days",
        "requirement_value": 30,
        "rarity": "rare",
    },
    {
        "key": "streak_60",
        "name": "Two Months Strong",
        "description": "Work out 60 days in a row",
        "icon_name": "Crown",
        "category": "consistency",
        "xp_reward": 1000,
        "requirement_type": "streak_days",
        "requirement_value": 60,
        "rarity": "epic",
    },
    {
        "key": "streak_100",
        "name": "Century Streak",
        "description": "Work out 100 days in a row",
        "icon_name": "Star",
        "category": "consistency",
        "xp_reward": 2000,
        "requirement_type": "streak_days",
        "requirement_value": 100,
        "rarity": "epic",
    },
    {
        "key": "streak_180",
        "name": "Half-Year Hero",
        "description": "Work out 180 days in a row",
        "icon_name": "Star",
        "category": "consistency",
        "xp_reward": 3000,
        "requirement_type": "streak_days",
        "requirement_value": 180,
        "rarity": "legendary",
    },
    {
        "key": "streak_365",
        "name": "Year-Round Athlete",
        "description": "Work out every single day for a year",
        "icon_name": "Crown",
        "category": "consistency",
        "xp_reward": 5000,
        "requirement_type": "streak_days",
        "requirement_value": 365,
        "rarity": "legendary",
    },

    # ── NUTRITION (7) ────────────────────────────────────────────────────────
    {
        "key": "first_meal",
        "name": "Food Logger",
        "description": "Log your first meal",
        "icon_name": "Utensils",
        "category": "nutrition",
        "xp_reward": 10,
        "requirement_type": "meal_count",
        "requirement_value": 1,
        "rarity": "common",
    },
    {
        "key": "meals_50",
        "name": "Mindful Eater",
        "description": "Log 50 meals",
        "icon_name": "Utensils",
        "category": "nutrition",
        "xp_reward": 100,
        "requirement_type": "meal_count",
        "requirement_value": 50,
        "rarity": "common",
    },
    {
        "key": "meals_200",
        "name": "Macro Master",
        "description": "Log 200 meals",
        "icon_name": "ChefHat",
        "category": "nutrition",
        "xp_reward": 250,
        "requirement_type": "meal_count",
        "requirement_value": 200,
        "rarity": "rare",
    },
    {
        "key": "meals_500",
        "name": "Nutrition Nerd",
        "description": "Log 500 meals",
        "icon_name": "ChefHat",
        "category": "nutrition",
        "xp_reward": 500,
        "requirement_type": "meal_count",
        "requirement_value": 500,
        "rarity": "epic",
    },
    {
        "key": "nutrition_7day",
        "name": "Consistent Fueler",
        "description": "Log meals 7 days in a row",
        "icon_name": "Salad",
        "category": "nutrition",
        "xp_reward": 150,
        "requirement_type": "nutrition_streak",
        "requirement_value": 7,
        "rarity": "rare",
    },
    {
        "key": "nutrition_goal_hit",
        "name": "On Target",
        "description": "Hit your calorie goal 5 times",
        "icon_name": "Target",
        "category": "nutrition",
        "xp_reward": 100,
        "requirement_type": "nutrition_goal_hits",
        "requirement_value": 5,
        "rarity": "common",
    },
    {
        "key": "protein_champion",
        "name": "Protein Champion",
        "description": "Hit your protein goal 30 times",
        "icon_name": "Beef",
        "category": "nutrition",
        "xp_reward": 300,
        "requirement_type": "protein_goal_hits",
        "requirement_value": 30,
        "rarity": "rare",
    },

    # ── BODY (4) ─────────────────────────────────────────────────────────────
    {
        "key": "first_body_metric",
        "name": "Body Aware",
        "description": "Log your first body measurement",
        "icon_name": "Scale",
        "category": "body",
        "xp_reward": 20,
        "requirement_type": "body_metric_count",
        "requirement_value": 1,
        "rarity": "common",
    },
    {
        "key": "body_metrics_10",
        "name": "Tracking Progress",
        "description": "Log 10 body measurements",
        "icon_name": "Scale",
        "category": "body",
        "xp_reward": 100,
        "requirement_type": "body_metric_count",
        "requirement_value": 10,
        "rarity": "common",
    },
    {
        "key": "body_metrics_30",
        "name": "Transformation Tracker",
        "description": "Log 30 body measurements",
        "icon_name": "LineChart",
        "category": "body",
        "xp_reward": 200,
        "requirement_type": "body_metric_count",
        "requirement_value": 30,
        "rarity": "rare",
    },
    {
        "key": "first_goal_reached",
        "name": "Goal Crusher",
        "description": "Reach your first body goal",
        "icon_name": "CheckCircle",
        "category": "body",
        "xp_reward": 300,
        "requirement_type": "goals_reached",
        "requirement_value": 1,
        "rarity": "rare",
    },

    # ── LEVELS (3) ────────────────────────────────────────────────────────────
    {
        "key": "level_5",
        "name": "Rising Star",
        "description": "Reach Level 5",
        "icon_name": "Star",
        "category": "consistency",
        "xp_reward": 200,
        "requirement_type": "level",
        "requirement_value": 5,
        "rarity": "rare",
    },
    {
        "key": "level_8",
        "name": "Elite Athlete",
        "description": "Reach Level 8",
        "icon_name": "Crown",
        "category": "consistency",
        "xp_reward": 500,
        "requirement_type": "level",
        "requirement_value": 8,
        "rarity": "epic",
    },
    {
        "key": "level_10",
        "name": "Fitness Legend",
        "description": "Reach the max level — Level 10",
        "icon_name": "Crown",
        "category": "consistency",
        "xp_reward": 2000,
        "requirement_type": "level",
        "requirement_value": 10,
        "rarity": "legendary",
    },
]


async def seed_achievements(db):
    from sqlalchemy import select
    from app.models.gamification import AchievementDefinition

    result = await db.execute(select(AchievementDefinition).limit(1))
    if result.scalar():
        return  # Already seeded

    for data in ACHIEVEMENTS:
        a = AchievementDefinition(**data)
        db.add(a)
    await db.commit()
    print(f"[seed] Inserted {len(ACHIEVEMENTS)} achievement definitions.")
